### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hatzel** [lxucs/coref-hoi#4]
The repo does not contain any license specification. It would be great if you could license it explicitly under a FOSS license so that further research can build upon this great code!
Personally I'd suggest the MIT license but a Apache or a GPL variety could also be a great choice.

Most of these licenses require attribution in source code distributions so you would have to be credited (as you should be :smiley:).

**Comment by lxucs** [comment]
Thanks for the suggestion! I will add a license soon.
