### ISSUE TITLE
Running on our own CoNLL-U files

### ISSUE THREAD

**Issue by sabyasachee** [lxucs/coref-hoi#6]
I have been able to run the models on the OntoNotes test set, but how do we get predictions for our own CoNLL-U files?

**Comment by lxucs** [comment]
Sorry for my late reply. I will add a script soon to perform prediction on custom input.

**Comment by sabyasachee** [comment]
Thank you. I was able to get predictions on my own CoNLL files but I had to edit the code. It would be great if you could add that functionality, as you said.

**Comment by lxucs** [comment]
I have just pushed a commit to include a script for prediction on custom input. Let me know if you have more questions.
