### ISSUE TITLE
Data Set up issue in Basic Set up

### ISSUE THREAD

**Issue by sushantakpani** [lxucs/coref-hoi#7]
1. Install Python3 dependencies: pip install -r requirements.txt
   2.  Create a directory for data that will contain all data files, models and log files; set data_dir = /path/to/data/dir in experiments.conf
    
After step 1 and 2 I tried step 3 of the Basic setup

Prepare dataset (requiring OntoNotes 5.0 corpus): ./setup_data.sh /path/to/ontonotes /path/to/data/dir

.
.

reference-coreference-scorers/v8.01/test/DataFiles/TC-N.key
reference-coreference-scorers/v8.01/test/test.pl
reference-coreference-scorers/v8.01/test/TestCases.README
**bash: conll-2012/v3/scripts/skeleton2conll.sh: No such file or directory**

Though  there exists a coref_hoi/data/dir/conll-2012/v3/scripts/skeleton2conll.sh file.
Do I need to change any other file prior to running setup_data.sh ?

**Comment by lxucs** [comment]
Hi, the conll-2012 directory needs to be placed under the code directory instead of the data dir.

**Comment by lxucs** [comment]
Hi, the path was not correct in the script. I have just updated the script and it should work now. Sorry for the confusion.

**Comment by sushantakpani** [comment]
Thanks for this update.
